# Generated by Django 5.0.6 on 2024-05-31 19:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipeProject", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="receipe",
            old_name="description",
            new_name="Receipe_desc",
        ),
        migrations.RenameField(
            model_name="receipe",
            old_name="name",
            new_name="receipe_name",
        ),
    ]
