# Generated by Django 5.0.6 on 2024-05-31 19:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipeProject", "0002_rename_description_receipe_receipe_desc_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="receipe",
            old_name="Receipe_desc",
            new_name="receipe_desc",
        ),
    ]
