# Generated by Django 5.1.7 on 2025-04-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeProject', '0004_receipe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='receipe_image',
            field=models.ImageField(upload_to='receipe/'),
        ),
    ]
