# Generated by Django 5.0.6 on 2024-05-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="name",
        ),
        migrations.AlterField(
            model_name="student",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
