# Generated by Django 5.0.6 on 2024-05-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_remove_product_name_alter_student_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_name", models.CharField(max_length=500)),
                ("speed", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
